/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FoundersVisionRouteImport } from './routes/founders-vision'
import { Route as EmbroideryRouteImport } from './routes/embroidery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as AdminProductsRouteImport } from './routes/admin/products'

const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersVisionRoute = FoundersVisionRouteImport.update({
  id: '/founders-vision',
  path: '/founders-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbroideryRoute = EmbroideryRouteImport.update({
  id: '/embroidery',
  path: '/embroidery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embroidery': typeof EmbroideryRoute
  '/founders-vision': typeof FoundersVisionRoute
  '/journal': typeof JournalRoute
  '/legacy': typeof LegacyRoute
  '/our-story': typeof OurStoryRoute
  '/philosophy': typeof PhilosophyRoute
  '/admin/products': typeof AdminProductsRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embroidery': typeof EmbroideryRoute
  '/founders-vision': typeof FoundersVisionRoute
  '/journal': typeof JournalRoute
  '/legacy': typeof LegacyRoute
  '/our-story': typeof OurStoryRoute
  '/philosophy': typeof PhilosophyRoute
  '/admin/products': typeof AdminProductsRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embroidery': typeof EmbroideryRoute
  '/founders-vision': typeof FoundersVisionRoute
  '/journal': typeof JournalRoute
  '/legacy': typeof LegacyRoute
  '/our-story': typeof OurStoryRoute
  '/philosophy': typeof PhilosophyRoute
  '/admin/products': typeof AdminProductsRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embroidery'
    | '/founders-vision'
    | '/journal'
    | '/legacy'
    | '/our-story'
    | '/philosophy'
    | '/admin/products'
    | '/collections/$category'
    | '/product/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embroidery'
    | '/founders-vision'
    | '/journal'
    | '/legacy'
    | '/our-story'
    | '/philosophy'
    | '/admin/products'
    | '/collections/$category'
    | '/product/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/embroidery'
    | '/founders-vision'
    | '/journal'
    | '/legacy'
    | '/our-story'
    | '/philosophy'
    | '/admin/products'
    | '/collections/$category'
    | '/product/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbroideryRoute: typeof EmbroideryRoute
  FoundersVisionRoute: typeof FoundersVisionRoute
  JournalRoute: typeof JournalRoute
  LegacyRoute: typeof LegacyRoute
  OurStoryRoute: typeof OurStoryRoute
  PhilosophyRoute: typeof PhilosophyRoute
  AdminProductsRoute: typeof AdminProductsRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders-vision': {
      id: '/founders-vision'
      path: '/founders-vision'
      fullPath: '/founders-vision'
      preLoaderRoute: typeof FoundersVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embroidery': {
      id: '/embroidery'
      path: '/embroidery'
      fullPath: '/embroidery'
      preLoaderRoute: typeof EmbroideryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbroideryRoute: EmbroideryRoute,
  FoundersVisionRoute: FoundersVisionRoute,
  JournalRoute: JournalRoute,
  LegacyRoute: LegacyRoute,
  OurStoryRoute: OurStoryRoute,
  PhilosophyRoute: PhilosophyRoute,
  AdminProductsRoute: AdminProductsRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  ProductSlugRoute: ProductSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
